name: Build on Merge to Dev

on:
  push:
    branches:
      - dev

jobs:
    main:
        name: Deploy to Render
        runs-on: ubuntu-latest
        steps:
          - name: Trigger deployment
            uses: sws2apps/render-deployment@main 
            with:
              serviceId: ${{ secrets.RENDER_SERVICE_ID }}
              apiKey: ${{ secrets.RENDER_API_KEY }}
              multipleDeployment: false 