name: Tests & Lint CI

on:
  push:
    branches:
      - 'feature/*'

jobs:
  install-dependencies:
    name: Run Tests & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Linter
        run: npm run lint

  tests:
    name: Test
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Tests
        run: npm run test