name: Tests & Lint CI

on:
  push:
    branches:
      - 'feature/*'

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 18
      - name: Depedencias
        run: npm ci
      - name: Lint
        run: npm run lint
  
  unit-test:
    name: Test
    needs: [linter]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: 18
      - name: Depedencias
        run: npm ci
      - name: Test
        run: npm run test